### ISSUE TITLE
How does the org-mode maintain consistency

### ISSUE THREAD

**Issue by drudru** [ajtoo/vscode-org-mode#102]
I want to start using this with visual studio code.
I have an internals / developer question.

How do you maintain consistency with the document?
Do you re-parse the document every time a key is hit or an action is taken?
Or do you control how the document gets mutated to prevent re-parsing.

Thx.

**Comment by ajtoo** [comment]
Hi dru, the extension is currently not up to feature parity with actual org-mode. However, to answer your question: in most things we try to simply read/parse relevant sections of the document via the API provided by the vscode team. Our priorities are currently centered around things that can be done as wysiwg since that's primarily what vscode provides for. As things stand, me and the other co-creators are a bit busy at the moment. However, you are welcome to contribute (and refactor) as you wish. Submit a pull request and I will likely accept it.
